<?php

namespace App;


use Illuminate\Database\Eloquent\Model;

class Member extends Model
{
    //指定表名
    protected $table = 'member';

    //指定主键为id
    protected $primaryKey ='id';

    //自动维护时时间戳
    public $timestamps = true;

    //指定允许批量赋值的字段(即哪些字段可以重复)
    public $fillable = ['name' ,'age'];

    //指定不允许批量赋值的字段
    public $guarded =[];
//    public $

   protected function getDateFormat()
   {
       return parent::getDateFormat(); // TODO: Change the autogenerated stub
   }

    protected function asDateTime($val)
    {
        return $val;
    }
}